### PR TITLE
added some recent publications

### PR DESCRIPTION
**Pull request by preslav**

### CODE REVIEW

**Comment by AlaaHamoudah** [comment]
@preslav is this PR still valid?

**Comment by preslav** [comment]
What is PR? Public Relations?

**Comment by AlaaHamoudah** [comment]
@preslav PR stands for a pull request

**Comment by preslav** [comment]
yes, but I will make even a newer one.

**Comment by AlaaHamoudah** [comment]
So I will close this one and looking forward to the recent one. Ok?

**Comment by preslav** [comment]
ok

**Pull request closed without merging**
